### ISSUE TITLE
Title and logo feel a bit large

### ISSUE THREAD

**Issue by jeremyloyd** [sparkbox/apprentices-page#43]
Can we get a bit closer to the Sketch file proportions and spacing:

![image](https://cloud.githubusercontent.com/assets/1679752/4667986/b6182d3a-5561-11e4-8a7d-138bfad6d059.png)

**Comment by bryanbraun** [comment]
Looks like this was fixed in #47 and #49, but the issue wasn't closed. Closing it now!
