### ISSUE TITLE
Logo on Learn more and apply page seems big

### ISSUE THREAD

**Issue by jeremyloyd** [sparkbox/apprentices-page#45]
I think we could use whatever size we arrive at on the homepage

![pasted_image_10_16_14__2_47_pm](https://cloud.githubusercontent.com/assets/1679752/4668402/fc70497c-5564-11e4-9aa6-326f6e6a515e.jpg)

**Comment by bryanbraun** [comment]
Looks like this was fixed in #51 but the issue was never closed (I confirmed visually). Closing it now.
